[package]
name = "kernel"
version = "0.1.0"
authors = ["Grant Jurgensen <gajurgensen@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
#rlibc = "1.0" # Used for memcpy, memmove, memset, and memcmp
